package test.es.upm.emse.enteridea.adapter.dto;

import org.junit.Test;

import es.upm.emse.enteridea.adapter.dto.DTOFactory;
import es.upm.emse.enteridea.adapter.dto.IdeaDTO;
import es.upm.emse.enteridea.adapter.dto.exception.DTOFactoryException;
import es.upm.emse.enteridea.persistence.dao.GenericDAO;
import es.upm.emse.enteridea.persistence.dao.imp.GenericDAOImp;
import es.upm.emse.enteridea.persistence.entity.Idea;
import junit.framework.TestCase;

/**
 * The class <code>DTOFactoryTest</code> contains tests for the class {@link
 * <code>DTOFactory</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 28/11/13 2:24
 *
 * @author ottoabreu
 *
 * @version $Revision$
 * 
 * The idea with id 1 must exist and have at least 1 vote and 1 comment 
 */
public class DTOFactoryTest extends TestCase {

	private DTOFactory<IdeaDTO> ideaFactory;
	private Idea idea; 
	
	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public DTOFactoryTest(String name) {
		super(name);
	}

	/**
	 * Perform pre-test initialization
	 *
	 * @throws Exception
	 *
	 * @see TestCase#setUp()
	 */
	@SuppressWarnings("unchecked")
	protected void setUp() throws Exception {
		super.setUp();
		
		 GenericDAO<Idea, Long> ideaDao = new GenericDAOImp<Idea,Long>(Idea.class);
		
		this.idea = ideaDao.read((long)1); 
		this.ideaFactory = (DTOFactory<IdeaDTO>) DTOFactory.getInstance(idea, IdeaDTO.class);
		
		// Add additional set up code here
	}

	/**
	 * Perform post-test clean up
	 *
	 * @throws Exception
	 *
	 * @see TestCase#tearDown()
	 */
	protected void tearDown() throws Exception {
		super.tearDown();
		this.idea = null;
		this.ideaFactory = null;
	}

	/**
	 * Run the T generateDTOFromEntity() method test
	 */
	@Test
	public void testGenerateDTOFromEntity() {
		try {
			IdeaDTO ideaDto = this.ideaFactory.generateDTOFromEntity();
			System.out.println("ideaDTO"+ideaDto);
			assertTrue(compareIdeaDTOandEntity(ideaDto));
			
		} catch (DTOFactoryException e) {
			fail(e.getMessage());
		}
	}
	
	private boolean compareIdeaDTOandEntity(IdeaDTO ideaDto){
		boolean equal = false;
		int cont = 0;
		
		if (ideaDto.getIdeaiId() == this.idea.getIdeaiId()){
			cont++;
			System.out.println("id ok");
		}
		
		if (ideaDto.getTitle().equals(this.idea.getTitle())){
			cont++;
			System.out.println("title ok");
		}
		
		if (ideaDto.getDescription().equals(this.idea.getDescription())){
			cont++;
			System.out.println("description ok");
		}
		
		if (ideaDto.getTopicDescription().equals(this.idea.getTopic().getTopicDescription())){
			cont++;
			System.out.println("topic description ok");
		}
		
		
		if (ideaDto.getOwnerFirstName().equals(this.idea.getIdeaOwner().getFirstName())){
			cont++;
			System.out.println("firstname ok");
		}
		
		
		if (ideaDto.getOwnerLastName().equals(this.idea.getIdeaOwner().getLastName())){
			cont++;
			System.out.println("lastname ok");
		}
		
		System.out.println("nickname entity:"+this.idea.getIdeaOwner().getNickname());
		System.out.println("nickname dto:"+ideaDto.getOwnerNickName());
		if (ideaDto.getOwnerNickName().equals(this.idea.getIdeaOwner().getNickname())){
			cont++;
			System.out.println("nickname ok");
		}
		
		System.out.println("email entity:"+this.idea.getIdeaOwner().getEmail());
		System.out.println("email dto:"+ideaDto.getOwnerEmail());
		if (ideaDto.getOwnerEmail().equals(this.idea.getIdeaOwner().getEmail())){
			cont++;
			System.out.println("email ok");
		}
		
		
		if (ideaDto.getDateToShow().equals(this.idea.getDateToShow())){
			cont++;
			System.out.println("datetoshow ok");
		}
		
		
		
		if (ideaDto.getModDateToShow().equals(this.idea.getModDateToShow())){
			cont++;
			System.out.println("modDate ok");
		}
		System.out.println("comments entity:"+idea.getIdeaComments().size());
		System.out.println("comments dto:"+ideaDto.getIdeaComments().size());
		
		if(ideaDto.getIdeaComments().size() == idea.getIdeaComments().size()){
			cont++;
			System.out.println("ideaComment ok");
		}
		
		if(ideaDto.getVotes().size() == idea.getVotes().size()){
			cont++;
			System.out.println("idea votes ok");
		}
	
		if(cont == 12){
			equal = true;
		}
		
		return equal;
	}
}



/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = true
 * createTearDown = true
 * createTestFixture = false
 * createTestStubs = false
 * methods = generateDTOFromEntity()
 * package = test.es.upm.emse.enteridea.adapter
 * package.sourceFolder = entrepreneur_ideas/src
 * superclassType = junit.framework.TestCase
 * testCase = DTOFactoryTest
 * testClassType = es.upm.emse.enteridea.adapter.dto.DTOFactory
 */